const cfg=window.CAFE_SUPABASE||{};
const configured=cfg.url&&cfg.anonKey&&!cfg.url.includes('YOUR_');
const $=id=>document.getElementById(id);
if(!configured){$('auth-state').textContent='ابتدا Supabase URL و anon key را در js/supabase-config.js وارد کن.';$('login-card').classList.add('hidden');throw new Error('Supabase not configured')}
const sb=window.supabase.createClient(cfg.url,cfg.anonKey);
const split=v=>v.split(',').map(x=>x.trim()).filter(Boolean);
const msg=(id,text)=>$(id).textContent=text||'';
let editing=null;

async function isAdmin(){const {data:{user}}=await sb.auth.getUser();if(!user)return false;const {data}=await sb.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();return !!data}
async function refreshAuth(){const ok=await isAdmin();$('login-card').classList.toggle('hidden',ok);$('dashboard').classList.toggle('hidden',!ok);$('logout').classList.toggle('hidden',!ok);$('auth-state').textContent=ok?'وارد شده‌اید':'وارد نشده‌اید';if(ok){await Promise.all([loadProducts(),loadSettings()])}}
$('login').onclick=async()=>{msg('login-msg','در حال ورود…');const {error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){msg('login-msg',error.message);return}if(!(await isAdmin())){await sb.auth.signOut();msg('login-msg','این حساب دسترسی ادمین ندارد.');return}msg('login-msg','');refreshAuth()}
$('logout').onclick=async()=>{await sb.auth.signOut();refreshAuth()};

async function loadProducts(){const {data,error}=await sb.from('products').select('*').order('sort_order').order('created_at');if(error)return;const root=$('product-list');root.innerHTML='';for(const p of data||[]){const el=document.createElement('div');el.className='item';el.innerHTML=`<img src="${p.image_url||''}" alt=""><div><h3>${p.name}</h3><p>${p.price_small||0}${p.price_large?' / '+p.price_large:''} هزار تومان · ${p.is_available?'موجود':'ناموجود'}</p></div><div class="actions"><button class="btn ghost edit">ویرایش</button><button class="btn danger del">حذف</button></div>`;el.querySelector('.edit').onclick=()=>openEditor(p);el.querySelector('.del').onclick=()=>removeProduct(p);root.appendChild(el)}}
function openEditor(p=null){editing=p;$('editor').classList.remove('hidden');$('editor-title').textContent=p?'ویرایش محصول':'محصول جدید';$('product-id').value=p?.id||'';$('p-name').value=p?.name||'';$('p-category').value=p?.category||'espresso';$('p-small').value=p?.price_small||'';$('p-large').value=p?.price_large||'';$('p-desc').value=p?.description||'';$('p-tags').value=(p?.tags||[]).join('، ');$('p-allergens').value=(p?.allergens||[]).join('، ');$('p-available').checked=p?.is_available??true;$('p-vegan').checked=!!p?.is_vegan;$('p-dairy').checked=!!p?.is_dairy_free;$('p-sugar').checked=!!p?.is_sugar_free;$('p-image').value='';$('editor').scrollIntoView({behavior:'smooth'})}
$('new-product').onclick=()=>openEditor();$('cancel-edit').onclick=()=>{$('editor').classList.add('hidden');editing=null};
async function uploadImage(file){if(!file)return editing?.image_url||null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`products/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from('menu-images').upload(path,file,{upsert:false,contentType:file.type});if(error)throw error;return sb.storage.from('menu-images').getPublicUrl(path).data.publicUrl}
$('save-product').onclick=async()=>{try{msg('product-msg','در حال ذخیره…');const name=$('p-name').value.trim();if(!name)throw new Error('نام محصول الزامی است.');const image_url=await uploadImage($('p-image').files[0]);const payload={name,category:$('p-category').value,price_small:Number($('p-small').value||0),price_large:$('p-large').value?Number($('p-large').value):null,description:$('p-desc').value.trim(),tags:split($('p-tags').value.replaceAll('،',',')),allergens:split($('p-allergens').value.replaceAll('،',',')),is_available:$('p-available').checked,is_vegan:$('p-vegan').checked,is_dairy_free:$('p-dairy').checked,is_sugar_free:$('p-sugar').checked,image_url};const q=editing?sb.from('products').update(payload).eq('id',editing.id):sb.from('products').insert(payload);const {error}=await q;if(error)throw error;msg('product-msg','ذخیره شد.');$('editor').classList.add('hidden');editing=null;await loadProducts()}catch(e){msg('product-msg',e.message)}};
async function removeProduct(p){if(!confirm(`«${p.name}» حذف شود؟`))return;const {error}=await sb.from('products').delete().eq('id',p.id);if(error)alert(error.message);else loadProducts()}

async function loadSettings(){const {data}=await sb.from('site_settings').select('*').eq('id',1).maybeSingle();if(!data)return;$('s-instagram-id').value=data.instagram_id||'';$('s-instagram-url').value=data.instagram_url||'';$('s-telegram-url').value=data.telegram_url||'';$('s-whatsapp-url').value=data.whatsapp_url||'';$('s-phone').value=data.phone||'';$('s-address').value=data.address||''}
$('save-settings').onclick=async()=>{msg('settings-msg','در حال ذخیره…');const payload={id:1,instagram_id:$('s-instagram-id').value.trim(),instagram_url:$('s-instagram-url').value.trim(),telegram_url:$('s-telegram-url').value.trim(),whatsapp_url:$('s-whatsapp-url').value.trim(),phone:$('s-phone').value.trim(),address:$('s-address').value.trim(),updated_at:new Date().toISOString()};const {error}=await sb.from('site_settings').upsert(payload);msg('settings-msg',error?error.message:'ذخیره شد.')};
refreshAuth();
